### ISSUE TITLE
Task 2 - Report

### ISSUE THREAD

**Issue by tooxoot** [tooxoot/FTVS_SS17#6]
#### TODOS:
1. Performing the error-injection-experiment as described in task 2.
2. Writing a report describing the experiment's results.

**Comment by tooxoot** [comment]
- Currently performing experiments for mode 3 and 4.
- Will add report document into reports folder.

**Comment by skjunobl** [comment]
Starting with the error-injection-experiment for task 2. (mode 1 & 2)

**Comment by tooxoot** [comment]
### Finished
- Experiments for mode 1, 3 and 4
- Adding report document
- Adding experiment's results to the report

### @skjunobl 
- Also did experiments for mode  2
- The numbers for mode 2 are kind of odd! Definitely should discuss this tomorow.
